openapi: 3.0.1

info:
  title: EBP back-end api
  description: The EBP backend
#   termsOfService:
  contact:
    name: Elastos.Community
    url: https://github.com/elastos/Elastos.Community/issues
#    email: liyangwood@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

servers:
- url: http://localhost:3000
  description: local server
- url: http://52.15.45.1:3000
  description: dev server

tags:
- name: test
  description: test api, only available in dev env.
- name: user
  description: user api
- name: team
  description: team api

components:
  schemas:

  securitySchemes:
#    session-token:
#      type: apiKey
#      in: cookie
#      name: ebp-token
    api-token:
      type: apiKey
      in: header
      name: api-token

  UnauthorizedError:
    description: ebp-token is missing or invalid

paths:
  /test/hello:
    $ref: "./path/test/hello.yml"

  /user/register:
    $ref: "./path/user/register.yml"
  /user/login:
    $ref: "./path/user/login.yml"
  /user/current_user:
    $ref: './path/user/current_user.yml'
  /user/change_password:
    $ref: './path/user/change_password.yml'

  /team/create:
    $ref: './path/team/create.yml'

  /task/{taskId}:
    $ref: './path/task/get.yml'
